drop table if exists badger CASCADE;

create table badger (
    id bigint generated by default as identity,
    age integer not null,
    habitat varchar(255),
    name varchar(255),
    primary key (id)
);